example_app/urls.py
from django.urls import path
from example_app.views import index

app_name = 'example_app'

urlpatterns = [
    path('', index, name='index'),
]

katalog/urls.py
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

mywatchlist/urls.py
from django.urls import path
from mywatchlist.views import show_watchlist, show_json, show_xml

app_name = 'mywatchlist'

urlpatterns = [
    path('', show_watchlist, name='show_watchlist'),
    path('json/', show_json, name='show_json'),
    path('xml/', show_xml, name='show_xml'),
    path('html/', show_watchlist, name='show_watchlist'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path
from todolist.views import logout_user, show_todolist, register, login_user, get_task, update_task, delete_task, show_json
from todolist.views import add_task
app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', get_task, name='create-task'),
    path('update-task/<str:pk>/', update_task, name='update-task'),
    path('delete-task/<str:pk>/', delete_task, name='delete-task'),
    path('json/', show_json, name='show_json'),
    path('add/', add_task, name='add'),
]

example_app/models.py
from django.db import models

# Create your models here.

katalog/models.py
from django.db import models

class CatalogItem(models.Model):
    item_name = models.CharField(max_length=255)
    item_price = models.BigIntegerField()
    item_stock = models.IntegerField()
    description = models.TextField()
    rating = models.IntegerField()
    item_url = models.URLField()

mywatchlist/models.py
from django.db import models

class WatchList(models.Model):
    watched = models.BooleanField()
    title = models.CharField(max_length=100)
    rating = models.IntegerField()
    release_date = models.CharField(max_length=20)
    review = models.CharField(max_length=222)

todolist/models.py
from django.db import models
from django.contrib.auth import settings

class ToDoList(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        null=True,
        blank=True)
    date = models.DateField(auto_now_add=True)
    title = models.CharField(max_length=100)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)

todolist/forms.py
from django import forms
from todolist.models import ToDoList

class TaskForm(forms.ModelForm):
    class Meta:
        model = ToDoList
        fields = ['title', 'description']

# class UpdateTask(forms.ModelForm):
#     class Meta:
#         model = ToDoList
#         fields = ['is_finished']

example_app/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

katalog/views.py
from django.shortcuts import render
from katalog.models import CatalogItem

def show_katalog(request):
    data_barang_katalog = CatalogItem.objects.all()
    context = {
        'list_barang': data_barang_katalog,
        'nama': 'Griselda Neysa Sadiya',
        'npm' : '2106751392'
    }
    return render(request, "katalog.html", context)

mywatchlist/views.py
from email import message
from django.shortcuts import render
from django.shortcuts import render
from mywatchlist.models import WatchList
from django.http import HttpResponse
from django.core import serializers

def show_watchlist(request):
    data_watchlist = WatchList.objects.all()

    movie_watched = 0
    movie_watched_no = 0
    message = ""
    for movie in data_watchlist:
        if (movie.watched == True):
            movie_watched+=1
        else:
            movie_watched_no+=1
    
    if(movie_watched>movie_watched_no):
        message = "Selamat, kamu sudah banyak menonton!"
    else: 
        message = "Wah, kamu masih sedikit menonton!"

    context = {
        'watchlist': data_watchlist,
        'nama': 'Griselda Neysa Sadiya',
        'npm' : '2106751392',
        'message' : message
    }
    return render(request, "mywatchlist.html", context)

def show_json(request):
    data = WatchList.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml(request):
    data = WatchList.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

todolist/views.py
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from django.core import serializers
from django.http import HttpResponse

from todolist.forms import TaskForm

import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.contrib.auth.decorators import login_required

from django.contrib.auth import logout

from django.contrib.auth import authenticate, login

from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

from django.shortcuts import render
from todolist.models import ToDoList

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    data_todolist = ToDoList.objects.filter(user=request.user)

    context = {
        'todolist' : data_todolist,
        'username' : request.user,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, 'todolist.html', context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

@login_required(login_url='/todolist/login/')
def get_task(request):
    form = TaskForm(request.POST)
    if request.method == "POST":
        print("Masuk post")
        if form.is_valid():
            print("Masuk valid")
            tempsave = form.save(commit=False)
            tempsave.user = request.user
            form.save()
            return(redirect('todolist:show_todolist'))

    context = {'forms': form}
    return render(request, 'task.html', context)

@login_required(login_url='/todolist/login/')
def update_task(request, pk):
    model = ToDoList.objects.get(id=pk)

    if(model.is_finished == False):
        model.is_finished = True
    else:
        model.is_finished = False
    model.save()
    return redirect('todolist:show_todolist')


@login_required(login_url='/todolist/login/')
def delete_task(request, pk):
    ToDoList.objects.get(id=pk).delete()
    return(redirect('todolist:show_todolist'))
    
def show_json(request):
    data = ToDoList.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@login_required(login_url='/todolist/login/')
@csrf_exempt
def add_task(request):
    form = TaskForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            newTask = ToDoList.objects.create(user=request.user,title=title, description=description)
            data = {
                "pk" : newTask.pk,
                "title" : newTask.title,
                "description" : newTask.description,
                "is_finished" : newTask.is_finished,
                "date" : newTask.date,

            }
            newTask.save()
        return JsonResponse(data)

example_app/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Hello, world!</title>
{% endblock meta %}

{% block content %}
  <h1>Hello, world!</h1>
  <h3>This is example app for Django template</h3>
{% endblock content %}

katalog/templates/katalog.html
{% extends 'base.html' %}

 {% block content %}

  <h1 style = "text-align: center;">Lab 1 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>
  <style>
    table, th, td {
      border:1px solid black;
    }
  </style>

  <table style="width:100%">
    <tr>
      <th>Item Name</th>
      <th>Item Price</th>
      <th>Item Stock</th>
      <th>Rating</th>
      <th>Description</th>
      <th>Item URL</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for barang in list_barang %}
      <tr>
        <td>{{barang.item_name}}</td>
        <td>{{barang.item_price}}</td>
        <td>{{barang.item_stock}}</td>
        <td>{{barang.rating}}</td>
        <td>{{barang.description}}</td>
        <td>{{barang.item_url}}</td>
      </tr>
    {% endfor %}
  </table>

 {% endblock content %}

mywatchlist/templates/mywatchlist.html
{% extends 'base.html' %}

 {% block content %}

  <h1 style = "text-align: center;">Tugas 2 Assignment PBP/PBD</h1>

  <h5>Name: </h5>
  <p>{{nama}}</p>

  <h5>Student ID: </h5>
  <p>{{npm}}</p>
  <style>
    table, th, td {
      border:1px solid black;
    }
  </style>

  <table style="width:100%">
    <tr>
      <th>Watched</th>
      <th>Movie Title</th>
      <th>Rating</th>
      <th>Release Date</th>
      <th>Review</th>
    </tr>
    {% comment %} Add the data below this line {% endcomment %}
    {% for movie in watchlist %}
      <tr>
        <td>{{movie.watched}}</td>
        <td>{{movie.title}}</td>
        <td>{{movie.rating}}</td>
        <td>{{movie.release_date}}</td>
        <td>{{movie.review}}</td>
      </tr>
    {% endfor %}
  </table>
  <h5>{{message}}</h5>

 {% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% load static %}
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <!-- Bootstrap CSS -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-u1OknCvxWvY5kfmNBILK2hRnQC3Pr17a+RTT6rIHI7NnikvbZlHgTPOOmMi466C8" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" /> -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
  <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" 
        rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
        crossorigin="anonymous"> -->
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% load static %}
  {% block content %}
  {% endblock content %}
</body>

</html>

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% load static %}
<link rel="stylesheet" href="{% static 'todolist/style.css' %}">
{% endblock meta %}

{% block content %}

<h2>Buat schedulemu di ToDoList</h2>
<div class="container-account" id="container">
    <div class="form-container sign-in-container">
        <form method="POST" action="">
            <h1>Login</h1>
            {% csrf_token %}
            <span>Pastikan username dan password kamu benar :)</span>
            <input type="text" name="username" placeholder="Username" class="form-control">
            <input type="password" name="password" placeholder="Password" class="form-control">
            <input class="btn btn-primary" type="submit" value="Login">
        </form>
        Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>
    </div>
    <div class="overlay-container">
        <div class="overlay">
         <div class="overlay-panel overlay-right">
          <h1>Hello, Friend!</h1>
          <p>Belum punya akun? Register dulu, yuk!</p>
          <button class="ghost" id="signUp"><a href="{% url 'todolist:register' %}">Register</a></button>
         </div>
        </div>
       </div>

    <div class="container">
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}  
    </div>
    
</div>

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% load static %}
<link rel="stylesheet" href="{% static 'todolist/style.css' %}">
{% endblock meta %}

{% block content %}  

<div class = "container-account">
    
    <h1 class="pageidentifier">Registrasi Akun Baru</h1>  

        <form method="POST" >  
            {% csrf_token %}  
            <table>  
                {{ form.as_table }}  
                <tr>  
                    <td></td>
                    <td><input type="submit" class="btn btn-primary btn-lg" name="submit" value="Daftar"/></td>  
                </tr>  
            </table>  
        </form>

    {% if messages %}  
        <ul>   
            {% for message in messages %}  
                <li>{{ message }}</li>  
                {% endfor %}  
        </ul>   
    {% endif %}

</div>  

{% endblock content %}

todolist/templates/task.html
{% extends 'base.html' %}

{% block meta %}
<title>Task Baru</title>
{% endblock meta %}

{% block content %}

<div class="form-container sign-in-container">
    <form method="POST" action="">
        <h1>Buat Task Baru</h1>
        {% csrf_token %}
        <span>Masukkan detail task kamu di sini</span>
        <input type="text" name="Judul Task" placeholder="Judul Task" class="form-control">
        <input type="text" name="Detail Task" placeholder="Detail Task" class="form-control">
        <input class="btn btn-primary" type="submit" value="Tambah Task">
    </form>
</div>

<div class = "container">

    <!-- <h1>Buat Task Baru</h1>

    <form method="POST" action="">
        {% csrf_token %}
        {{forms.as_table}}
        <br>
        <input type="submit" value="Tambah Task">
    </form> -->



    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}     
</div>

{% endblock content %}

todolist/templates/temporary.html
{% extends 'base.html' %}

 {% block content %}

  <h1 style = "text-align: center;">My To Do List</h1>

  <h5 style="text-align: center;">Let's finish the task, {{username}}!</h5>

  <style>
    table, th, td {
      border:1px solid black;
    }
  </style>

  <table style="width:100%">
    <tr>
      <th>Tanggal Pembuatan Task</th>
      <th>Judul Task</th>
      <th>Deskripsi Task</th>
      <th>Status Task</th>
      <th>Update Task</th>
      <th>Hapus Task</th>
    </tr>
    
    {% for task in todolist %}
      <tr>
        <td>{{task.date}}</td>
        <td>{{task.title}}</td>
        <td>{{task.description}}</td>

        {% if task.is_finished %}
            <td>Selesai</td>
        {% else %}
            <td>Belum Selesai</td>
        {% endif %}

        <td><button><a class="btn delete-btn" href="{% url 'todolist:update-task' task.id %}">Update</a></button></td>
        <td><button><a class="btn delete-btn" href="{% url 'todolist:delete-task' task.id %}">Hapus</a></button></td>
      </tr>
    {% endfor %}
  </table>
  <br><p>Login terakhir: {{last_login}}</p>
  <br>
  <button><a href="{% url 'todolist:create-task' %}">Tambah Task Baru</a>"</button>
  <button><a href="{% url 'todolist:logout' %}">Logout</a></button>

 {% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}


 {% block content %}
  <h2 style = "text-align: center;">My To Do List</h2>

  <h5 id="penyemangat" style="text-align: center;">Let's finish the task, {{username}}!</h5>

  <div class="container" id="card-task">

  </div>

<div class="container text-center">
  <!-- Button trigger modal -->
  <br>
  <button type="button" data-bs-toggle="modal" data-bs-target="#modal-add-task" class="btn btn-primary" >
    Add Task
  </button>
</div>

<!-- Modal -->
<div class="modal fade" id="modal-add-task" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal-add-task-title">Add Task</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form method="POST" id="form-add-task">
          {% csrf_token %}
          <input id="label-add-title" type="text" class="form-control" placeholder="Title">
          <input id="label-add-description" type="text" class="form-control" placeholder="Description">
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" data-bs-dismiss="modal" id="save-task-btn">Save changes</button>
      </div>
    </div>
  </div>
</div>

  <div class="container">
    <br><p>Login terakhir: {{last_login}}</p>
    <br>
    <button class="btn btn-warning"><a href="{% url 'todolist:create-task' %}">Tambah Task Baru</a></button>
    <button class="btn btn-danger"><a href="{% url 'todolist:logout' %}">Logout</a></button>
  </div>

 <script>
    function get_json(){
    $.get('/todolist/json/', function(data){
        var cardTask = ""
        for(var i = 0; i < data.length; i++){
          console.log(data[i])
          cardTask = `
          <div class="card">
            <div class="card-header">
              ${data[i].fields.is_finished ? `Selesai` : `Belum Selesai`}
            </div>
            <div class="card-body">
              <h5 class="card-title">${data[i].fields.title}</h5>
              <p class="card-text"><b>${data[i].fields.date}</b></p>
              <p class="card-text">${data[i].fields.description}</p>
              <a class="btn btn-primary" href="/todolist/update-task/${data[i].pk}">Update</a>
              <a class="btn btn-primary" href="/todolist/delete-task/${data[i].pk}">Hapus</a>
            </div>
          </div>
          `
          $('#card-task').append(cardTask);
        }
        
    })
    }

    function add_task(){
      $('#save-task-btn').click(function(){
        $.post("/todolist/add/",
        {
          title: $('#label-add-title').val(),
          description: $('#label-add-description').val(),
        },
        function(data){
          console.log($('#label-add-title').val())
          var cardTask = `
          <div class="card">
            <div class="card-header">
              ${data.is_finished ? `Selesai` : `Belum Selesai`}
            </div>
            <div class="card-body">
              <h5 class="card-title">${data.title}</h5>
              <p class="card-text"><b>${data.date}</b></p>
              <p class="card-text">${data.description}</p>
              <a class="btn btn-primary" href="/todolist/update-task/${data.pk}">Update</a>
              <a class="btn btn-primary" href="/todolist/delete-task/${data.pk}">Hapus</a>
            </div>
          </div>
          `
          $('#card-task').append(cardTask)
        })
        $("#form-add-task")[0].reset()
      })
    }

    $(document).ready(function(){
      get_json()
      add_task()
    });
 </script>
 {% endblock content %}